In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
from sklearn.datasets import load_digits
digits=load_digits()

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [20]:
lr=LogisticRegression(max_iter=100, solver='lbfgs',penalty='l2')
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

E:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.95

In [21]:
svm=SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9796296296296296

In [22]:
rf=RandomForestClassifier(n_estimators=100) #tree
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9722222222222222

In [24]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3) #means we break sample in 3 folder
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [25]:
kf.split([1,2,3,4,5,6,7,8,9]) # to return fold

<generator object _BaseKFold.split at 0x00000000094D30B0>

In [26]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [27]:
#
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [28]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

E:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.95

In [29]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.9796296296296296

In [40]:
from sklearn.model_selection import StratifiedKFold
fold=StratifiedKFold(n_splits=3)
score_logistic=[]
score_svm=[]
score_rf=[]
for train_index,test_index in fold.split(digits.data,digits.target):
    x_train,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index],\
                                   digits.target[train_index],digits.target[test_index]
    score_logistic.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    score_svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators=100),x_train,x_test,y_train,y_test))

E:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
E:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result

In [41]:
score_logistic

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [42]:
score_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [43]:
score_rf

[0.9365609348914858, 0.9632721202003339, 0.9298831385642737]

In [44]:
from sklearn.model_selection import cross_val_score

In [45]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

E:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
E:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [46]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [48]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.92777778, 0.90277778, 0.9637883 , 0.9637883 , 0.91643454])

In [52]:
score1=cross_val_score(RandomForestClassifier(n_estimators=20),digits.data,digits.target,cv=10)#cv=fold
np.average(score1)

0.9382247051520792